services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scapp
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - 5432:5432